from pathlib import Path
import json
import re

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.util import Inches, Pt

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "presentation/final_presentation.pptx"
OUTPUT = ROOT / "presentation/final_presentation_rehearsal.pptx"
MAIN = [1, 2, 4, 6, 7, 8, 9, 11, 12, 13, 14]
BACKUP = [3, 5, 10]

SCRIPTS = {
    1: (1, 10, "We studied what simple spatial and frequency features measure when they separate real photographs from generated images. Our theme is: same score, different story."),
    2: (1, 45, "Our sample contains three thousand GenImage images: half real, half generated by BigGAN, Stable Diffusion or ADM. Real images arrive as JPEGs of different sizes; generated images arrive as fixed-size PNGs. Original format and size alone separate the classes perfectly. We standardised both classes to 256 by 256 pixels, but that enlarges BigGAN twice and reduces other images. Equal output size does not erase processing history. We therefore compare seven spatial features, seven frequency features, and all fourteen together under JPEG compression and generator shift."),
    4: (1, 55, "Our contribution is a feature-level audit. We connect image processing operations to individual statistics, generator-specific scores, and actual classification decisions. The planned study tests matched JPEG and an unseen generator. Later diagnostics examine a shared resampling operation and clean-model JPEG transfer. Those diagnostics are exploratory. BigGAN pixels are identical between the two resampling conditions, while the real-image comparison changes. However, crop and training data also change, so this is not a pure causal test of resizing. Member two will explain the pipeline and planned results."),
    6: (2, 25, "The pipeline was fixed before processing. We check duplicates and image validity, then split by image group, so variants of an image cannot leak across train and test. All planned experiments share six hundred test images. Processing is applied equally to both classes, and confidence intervals use group bootstrap resampling."),
    7: (2, 30, "Spatial features measure brightness statistics, Sobel gradients, Laplacian variation and high-pass residuals. Frequency features measure power in different bands, spectral slope, directionality and peaks. Each feature set uses the same logistic-regression recipe. Standardisation is fitted on training data; model selection and the decision threshold use validation data only. AUROC measures ranking, with one half representing chance."),
    8: (2, 25, "E1 checks the baseline. E2 deliberately mismatches compression as a shortcut control. E3 applies the same JPEG quality to both classes and refits the model at each quality. E4 holds Stable Diffusion out of training; E5 combines that holdout with JPEG quality 75. R is a later crop-and-resampling diagnostic, separate from those planned experiments."),
    9: (2, 30, "Combined features have the best pooled scores. The baseline is 0.793, but on unseen Stable Diffusion under JPEG 75 it is only 0.629, with a confidence interval from 0.571 to 0.690. Frequency alone is 0.568 and spatial alone is 0.465. Combining them helps, yet the pooled score hides near-perfect BigGAN results and weaker diffusion results. Member three will explain why that distinction matters."),
    11: (3, 40, "The exploratory diagnostic compares the same 599 test images under the original processing and a native crop followed by shared enlargement. Pooled combined AUROC changes only from 0.796 to 0.802. But BigGAN frequency AUROC falls from nearly one to 0.828, and unseen Stable Diffusion spatial AUROC rises from 0.477 to 0.771. BigGAN images themselves are unchanged. These changes show sensitivity to the processing and reference data; crop and retraining prevent us from attributing everything to resampling alone."),
    12: (3, 35, "There is a second warning. In the original pipeline frequency beats spatial features; under the diagnostic that statistically supported advantage disappears. The interval does not establish spatial superiority. JPEG also affects decisions even when ranking changes little. With the clean model and threshold fixed, spatial false positives rise from 98 to 157 out of 300 real images at quality 50. Similar AUROC therefore does not guarantee similar decisions."),
    13: (3, 25, "Our limits are one dataset and split, three generators, one held-out family and one JPEG encoder. Real and generated content is not matched. The resampling diagnostic is post-hoc and changes the crop. The next useful experiment would hold field of view fixed while comparing processing, followed by rotating the held-out generator. These are future tests, not completed results."),
    14: (3, 10, "Our conclusion: simple features separate these samples, but their interpretation depends on processing history. Report results per generator and check decisions as well as pooled scores."),
}

REPLACEMENTS = {
    "Novelty: we audit features, not detectors": "Contribution: a feature-level processing audit",
    "Mechanism isolated": "Exploratory reference-data check",
    "BigGAN pixels identical; only the reals' resampling changes": "BigGAN pixels unchanged; crop and training data change",
    "No prior report of this feature-level protocol found  ·  we say “not found”, not “first”": "Contribution: trace processing effects through features, generator scores and decisions",
    "Prior work  ·  whole detectors": "Established questions",
    "Grommelt et al. 2024": "Compression history",
    "B-Free 2025": "Benchmark comparability",
    "Zhou & Wang 2026": "Resizing history",
    "This work  ·  14 named features": "This project  ·  14 named features",
    "same resampling for all": "native crop + shared 2x resize",
    "R: how every image is resampled": "R: exploratory crop + resampling",
    "Processed-file history": "File history (matched only)",
    "Controls (every experiment)": "Controls (matched conditions)",
    "Same pooled score, different story": "Similar pooled score, different generator results",
    "Resampling moves results more than JPEG or shift": "Processing changes scores and decisions",
    "Pooled score: unchanged.": "Pooled score: similar.",
    "R added after results; also narrows the field of view": "R is post-hoc; crop and models also change",
    "pre-specified native-resolution protocol (matched view)": "pre-specify comparison with matched field of view",
    "Right: with the same resampling for all, the three fake curves coincide.": "Right: the generator curves become closer under crop + shared enlargement.",
    "Why BigGAN is easy: our resize empties its high band": "BigGAN's high-band deficit is consistent with enlargement",
    "No resize": "no resize",
}


def build():
    prs = Presentation(SOURCE)
    original = list(prs.slides)
    entries = list(prs.slides._sldIdLst)
    for entry in entries:
        prs.slides._sldIdLst.remove(entry)
    for index in MAIN + BACKUP:
        prs.slides._sldIdLst.append(entries[index - 1])

    manifest = []
    for position, source_number in enumerate(MAIN + BACKUP, 1):
        slide = original[source_number - 1]
        for shape in slide.shapes:
            if shape.has_table:
                for row in shape.table.rows:
                    for cell in row.cells:
                        for paragraph in cell.text_frame.paragraphs:
                            for run in paragraph.runs:
                                for before, after in REPLACEMENTS.items():
                                    run.text = run.text.replace(before, after)
            if not shape.has_text_frame:
                continue
            for paragraph in shape.text_frame.paragraphs:
                for run in paragraph.runs:
                    for before, after in REPLACEMENTS.items():
                        run.text = run.text.replace(before, after)
            if re.fullmatch(r"\d+ / 14", shape.text):
                shape.text = f"{position} / {len(MAIN)}" if position <= len(MAIN) else "Backup"
            if shape.top == Inches(0.78):
                shape.width = Inches(10.0)
                for p in shape.text_frame.paragraphs:
                    for r in p.runs:
                        if r.font.size and r.font.size.pt > 24:
                            r.font.size = Pt(24)

        if source_number in SCRIPTS:
            member, seconds, script = SCRIPTS[source_number]
            slide.notes_slide.notes_text_frame.text = f"MEMBER {member} ({seconds} s). {script}"
            manifest.append({"slide": position, "source_slide": source_number,
                             "member": member, "seconds": seconds, "script": script})
        else:
            slide.notes_slide.notes_text_frame.text = {
                3: "BACKUP ONLY. Compare spatial, frequency and combined features under matched JPEG and generator holdout.",
                5: "BACKUP ONLY. Exploratory D1: pooled combined change +0.006 has a confidence interval spanning zero. Generator-specific changes accompany crop, reference-data and fitted-model changes. These results do not isolate a pure resampling effect.",
                10: "BACKUP ONLY. Mean spectra show a BigGAN high-band deficit under the original pipeline and closer generator curves under R. R shares a final crop-and-enlargement operation, while prior history and content remain unmatched. Do not attribute all differences to resizing alone.",
            }[source_number]

    diagnostic = original[10]
    box = diagnostic.shapes.add_textbox(Inches(0.6), Inches(5.65), Inches(12.1), Inches(0.23))
    box.text_frame.text = "Exploratory D1: 599 test images; crop, reference images and fitted models also change."
    for run in box.text_frame.paragraphs[0].runs:
        run.font.size = Pt(11)
        run.font.color.rgb = RGBColor(0x5D, 0x6D, 0x7E)

    prs.save(OUTPUT)
    (ROOT / "presentation/rehearsal_manifest.json").write_text(
        json.dumps({"source": str(SOURCE), "main_slides": len(MAIN), "backup_slides": len(BACKUP),
                    "planned_seconds_per_member": {str(m): sum(x[1] for x in SCRIPTS.values() if x[0] == m)
                                                   for m in (1, 2, 3)}, "slides": manifest}, indent=2),
        encoding="utf-8")
    print(f"Saved {OUTPUT}: {len(MAIN)} main slides, {len(BACKUP)} backups")


if __name__ == "__main__":
    build()
